### ISSUE TITLE
Other mod version on Modrinth?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [MrMelon54/draggable-resource-packs-fabric#12]
So I noticed on Modrinth below 1.19 there's no other versions. However on curseforge there's other versions below 1.19. I was wondering if it'd be possible to add those to the Modrinth site? However if you don't want to I'd understand

**Comment by mrmelon54** [comment]
I was planning to update them all for 1.20 including fixing the issues and converting all my mods to architectury thus having forge/fabric/quilt support. Then after that backporting down as many versions as people ask for. Possibly making use of legacy fabric as well?

Hopefully this answers your question.

As a side note: I would have liked to automatically copied all the releases from Curseforge to Modrinth but unfortunately the Curseforge API is locked down making that near impossible. Thus why I have newer 1.19.4 releases on Modrinth (via my automated system) but not on Curseforge.

**Comment by Aces-and-Jacks** [comment]
Ah ok. Sounds ambitious. Well thanks for answering and good luck with that. Should I just leave this open until that's done or close it?

**Comment by mrmelon54** [comment]
You can leave it open if you like.

**Comment by mrmelon54** [comment]
I am also in the process of making a fully automated mappings and `gradle.properties` updating Github bot, which would make a PR for each Minecraft version and after pulling the PR and testing I could merge the changes and my current system will automatically upload to Modrinth.

My idea is to automate my flow as much as possible so I barely have to do anything and thus can focus on releasing new mods.

**Comment by Aces-and-Jacks** [comment]
Automation is always nice. I'm not really familiar with coding but I hope it goes well

**Comment by icynstant** [comment]
please do it for 1.20.1 if you want and have free time, don't want to rush you. ur mod is very useful

**Comment by mrmelon54** [comment]
the 1.20 update should work for 1.20.1 without issues as its only a bug fix update, but I've started working on the 1.20 update so it shouldn't be too much longer
