### ISSUE TITLE
Pleeeez update this to 1.20

### ISSUE THREAD

**Issue by Dabbpool** [MrMelon54/draggable-resource-packs-fabric#13]
Dude you already know how annoying it is... We really need this because im constantly having to unload everything just to load something in to avoid them arrow buttons as much as possible but its so time consuming and it happens too often for my sanity and im losing marbles by the ton AAAAAAA Please and tanq

**Comment by mrmelon54** [comment]
Working on rewriting using architectury for forge/fabric/quilt so it will come out once that is done.

1.20 also seems to have broken the mod anyway so I have to fix that as well.

I also have other mods which I am also updating, some of which have been released already. I can only work so fast :rofl:
