### ISSUE TITLE
[Feature Request] Drag resource pack between available and selected

### ISSUE THREAD

**Issue by keatit71** [MrMelon54/draggable-resource-packs-fabric#2]
Being able to drag the resource packs in selected is helpful but i feel like it would help greatly to the utility if you could drag resource packs between available and selected as well.

**Comment by mrmelon54** [comment]
Yea I have already had requests for this. Unfortunately I'm not quite sure how I would implement it as the available packs list is ordered (not quite sure how) by the vanilla game and the selected packs has a specific order. If you have any ideas about how to do that then I would love to hear them and hopefully speed up the process to adding this feature.

**Comment by mrmelon54** [comment]
FYI: there was a discussion in my discord server about it but we never figured out how it was going to work

**Comment by 8MiYile** [comment]
This method requires overriding the Resourcepacks button and pointing to a new GUI
Mods like Sodium, which override the Video Settings option, use their own GUI

**Comment by mrmelon54** [comment]
I guess doing a complete remake of the resource pack screen would allow me to implement cross-disable/enabled list dragging without bodging into the vanilla resource pack menu

**Comment by mrmelon54** [comment]
Moved to https://github.com/mrmelon54/draggable_lists/issues/19
