### ISSUE TITLE
Servers won't move when dragging a server in the list.

### ISSUE THREAD

**Issue by OriginCode** [MrMelon54/draggable-resource-packs-fabric#6]
The server is draggable, however, the order just doesn't change and the surrounding server won't move.

Ver: 1.19.2
Mod Ver: 3.0.1+build.9
Quilt Ver: 0.17.4

**Comment by mrmelon54** [comment]
Report on https://github.com/mrmelon54/draggable_lists if this issue still occurs in 1.20
