### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by RaptaG** [MrMelon54/draggable-resource-packs-fabric#7]

**Comment by 8MiYile** [comment]
yes
we need support 1.19.3

**Comment by mrmelon54** [comment]
yeah it's coming

**Comment by RaptaG** [comment]
lesgo

**Comment by mrmelon54** [comment]
unfortunately like most people, I'm stuck in real life where I can't just code 24/7, so everything takes soooo much longer to complete

**Comment by 8MiYile** [comment]
@MrMelon54 It's okay, it's okay to have a start

**Comment by Felix14-v2** [comment]
wait, but the 1.19.2 version just works fine without any updates

**Comment by mrmelon54** [comment]
oh does it? I guess this is resolved then?

**Comment by Felix14-v2** [comment]
> oh does it? I guess this is resolved then?

Well, at least it doesn't crash for me and all its functions work fine. I guess people are just confused that the mod wasn't marked as compatible with 1.19.3 on Modrinth

**Comment by mrmelon54** [comment]
I have now marked it as compatible with 1.19.3

**Comment by RaptaG** [comment]
Lesgo
