### ISSUE TITLE
1.19.4?

### ISSUE THREAD

**Issue by Colorflow-exe** [MrMelon54/draggable-resource-packs-fabric#9]
1.19.4 plz

**Comment by solonovamax** [comment]
The latest version published to modrinth seems to run perfectly fine on 1.19.4. What is the issue?

**Comment by Colorflow-exe** [comment]
> 发布到 modrinth 的最新版本似乎在 1.19.4 上运行良好。问题是什么？

Sorry, I didn't notice it. :)
